### ISSUE TITLE
Add support for `Vec<u8>` in `RqliteArgumentRaw`

### ISSUE THREAD

**Issue by williamdes** [tomvoet/rqlite-rs#14]
See: https://rqlite.io/docs/api/api/#blob-data

Could this crate have support for Blobs ?
Typically `Vec<u8>`

Thank you for this very cool crate !
PS: (I have no idea if it it hard, but no using async in this crate would help me implement it ^^)

**Comment by tomvoet** [comment]
Hi! Thanks for your interest in this crate and for taking the time to contribute :)

I can take a look at implementing Blobs. That said, this could introduce some complexity. One approach might be to use [serde_bytes](https://crates.io/crates/serde_bytes), but we'd need to find a way to pass that information through the `rqlite-rs-macros` proc-macros.
Obviously this should probably be behind a feature.

What do you think?

Regarding the async stuff you mentioned, could you provide a bit more context? I'm not sure if i can follow. 
Thanks again!
