### ISSUE TITLE
query macro with Option values

### ISSUE THREAD

**Issue by magwoo** [tomvoet/rqlite-rs#15]
Is it possible, when using a query macro, to pass a value there as an Option argument, so that when Some(val) is inserted, a value is inserted, and when None is NULL

**Comment by tomvoet** [comment]
Hi @magwoo 

I created a small implementation, and would be happy if you take a look at it (#16).
Let me know what you think!

**Comment by magwoo** [comment]
thank you very much for the prompt response immediately with the solution
